"""
TOM Game Development Engine — Scaffolds and builds game projects.
Supports: Unity C#, Unreal C++, Godot GDScript, PyGame, Ren'Py.
Generates project structure, game scripts, scenes, and build configs.
"""
import os
import json
import shutil
import subprocess
from typing import Any, Dict, List, Optional
from tools.project_paths import project_path_str

class GameDevEngine:
    def __init__(self, output_dir: str = None):
        self.output_dir = output_dir or project_path_str("output", "games")
        os.makedirs(self.output_dir, exist_ok=True)
        self._engines = {
            "unity": "C#",
            "unreal": "C++",
            "godot": "GDScript",
            "pygame": "Python",
            "renpy": "Ren'Py",
        }

    def list_engines(self) -> Dict[str, str]:
        return self._engines

    def detect_installed_engines(self) -> Dict[str, Optional[str]]:
        installed = {}
        if shutil.which("unity") or shutil.which("Unity"):
            installed["unity"] = "Unity Editor"
        if shutil.which("UnrealEditor") or shutil.which("UE4Editor"):
            installed["unreal"] = "Unreal Engine"
        if shutil.which("godot") or shutil.which("Godot"):
            installed["godot"] = "Godot Engine"
        installed["pygame"] = "Always available (Python library)"
        return installed

    def scaffold_pygame(self, name: str, genre: str = "platformer") -> Dict[str, Any]:
        path = os.path.join(self.output_dir, name)
        os.makedirs(path, exist_ok=True)
        os.makedirs(os.path.join(path, "assets", "sprites"), exist_ok=True)
        os.makedirs(os.path.join(path, "assets", "sounds"), exist_ok=True)
        os.makedirs(os.path.join(path, "assets", "fonts"), exist_ok=True)

        config = {
            "title": name.replace("_", " ").title(),
            "width": 1024,
            "height": 768,
            "fps": 60,
            "genre": genre,
        }
        with open(os.path.join(path, "config.json"), "w") as f:
            json.dump(config, f, indent=2)

        main_code = self._pygame_main(name, genre)
        with open(os.path.join(path, "main.py"), "w") as f:
            f.write(main_code)

        with open(os.path.join(path, "requirements.txt"), "w") as f:
            f.write("pygame>=2.5.0\n")

        readme = f"# {config['title']}\n\nA {genre} game built with PyGame.\n\n## Setup\n```\npip install -r requirements.txt\npython main.py\n```\n"
        with open(os.path.join(path, "README.md"), "w") as f:
            f.write(readme)

        return {
            "status": "success",
            "path": path,
            "engine": "pygame",
            "files": ["main.py", "config.json", "requirements.txt", "README.md"],
            "message": f"PyGame project '{name}' scaffolded at {path}",
        }

    def _pygame_main(self, name: str, genre: str) -> str:
        return f'''"""
{name.replace("_", " ").title()} — A {genre} game built with PyGame
Generated by TOM GameDev Engine
"""
import pygame
import sys
import json
import math
import random

pygame.init()

with open("config.json") as f:
    CONFIG = json.load(f)

WIDTH = CONFIG["width"]
HEIGHT = CONFIG["height"]
FPS = CONFIG["fps"]
TITLE = CONFIG["title"]

screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption(TITLE)
clock = pygame.time.Clock()

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BLUE = (0, 100, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)

class Player(pygame.sprite.Sprite):
    def __init__(self, x, y):
        super().__init__()
        self.image = pygame.Surface((32, 48))
        self.image.fill(BLUE)
        self.rect = self.image.get_rect()
        self.rect.center = (x, y)
        self.vel_x = 0
        self.vel_y = 0
        self.speed = 5
        self.jump_power = -12
        self.gravity = 0.6
        self.on_ground = False

    def update(self, platforms):
        self.vel_x = 0
        keys = pygame.key.get_pressed()
        if keys[pygame.K_LEFT]:
            self.vel_x = -self.speed
        if keys[pygame.K_RIGHT]:
            self.vel_x = self.speed
        if keys[pygame.K_SPACE] and self.on_ground:
            self.vel_y = self.jump_power

        self.vel_y += self.gravity
        self.rect.x += self.vel_x
        self._collide(self.vel_x, 0, platforms)
        self.rect.y += self.vel_y
        self.on_ground = False
        self._collide(0, self.vel_y, platforms)

        if self.rect.bottom > HEIGHT:
            self.rect.bottom = HEIGHT
            self.vel_y = 0
            self.on_ground = True

    def _collide(self, vel_x, vel_y, platforms):
        for p in platforms:
            if self.rect.colliderect(p.rect):
                if vel_x > 0:
                    self.rect.right = p.rect.left
                if vel_x < 0:
                    self.rect.left = p.rect.right
                if vel_y > 0:
                    self.rect.bottom = p.rect.top
                    self.vel_y = 0
                    self.on_ground = True
                if vel_y < 0:
                    self.rect.top = p.rect.bottom
                    self.vel_y = 0

class Platform(pygame.sprite.Sprite):
    def __init__(self, x, y, w, h):
        super().__init__()
        self.image = pygame.Surface((w, h))
        self.image.fill(GREEN)
        self.rect = self.image.get_rect()
        self.rect.topleft = (x, y)

class Enemy(pygame.sprite.Sprite):
    def __init__(self, x, y):
        super().__init__()
        self.image = pygame.Surface((24, 24))
        self.image.fill(RED)
        self.rect = self.image.get_rect()
        self.rect.topleft = (x, y)
        self.dir = 1
        self.speed = 2

    def update(self):
        self.rect.x += self.speed * self.dir
        if self.rect.left < 0 or self.rect.right > WIDTH:
            self.dir *= -1

class Game:
    def __init__(self):
        self.running = True
        self.score = 0
        self.all_sprites = pygame.sprite.Group()
        self.platforms = pygame.sprite.Group()
        self.enemies = pygame.sprite.Group()
        self.player = Player(WIDTH // 2, HEIGHT - 100)
        self.all_sprites.add(self.player)
        ground = Platform(0, HEIGHT - 20, WIDTH, 20)
        self.platforms.add(ground)
        self.all_sprites.add(ground)
        for i in range(5):
            px = random.randint(100, WIDTH - 100)
            py = HEIGHT - 100 - i * 80
            plat = Platform(px, py, 80, 12)
            self.platforms.add(plat)
            self.all_sprites.add(plat)
            enemy = Enemy(random.randint(50, WIDTH - 50), py - 30)
            self.enemies.add(enemy)
            self.all_sprites.add(enemy)

    def handle_events(self):
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                self.running = False
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    self.running = False

    def update(self):
        self.player.update(self.platforms)
        self.enemies.update()
        hits = pygame.sprite.spritecollide(self.player, self.enemies, False)
        if hits:
            self.score -= 1

    def draw(self):
        screen.fill(BLACK)
        self.all_sprites.draw(screen)
        font = pygame.font.SysFont("Arial", 24)
        score_text = font.render(f"Score: {{self.score}}", True, WHITE)
        screen.blit(score_text, (10, 10))
        pygame.display.flip()

    def run(self):
        while self.running:
            self.handle_events()
            self.update()
            self.draw()
            clock.tick(FPS)
        pygame.quit()
        sys.exit()

if __name__ == "__main__":
    game = Game()
    game.run()
'''

    def generate_script(self, engine: str, task: str) -> Dict[str, Any]:
        engine = engine.lower()
        if engine not in self._engines:
            return {"status": "error", "message": f"Unsupported engine: {engine}. Supported: {list(self._engines.keys())}"}
        if engine == "unity":
            code = self._unity_script(task)
        elif engine == "unreal":
            code = self._unreal_script(task)
        elif engine == "godot":
            code = self._godot_script(task)
        else:
            code = f"# {engine} script generation for: {task}\n# TOM generated this scaffold\n"
        return {"status": "success", "engine": engine, "code": code, "language": self._engines[engine]}

    def _unity_script(self, task: str) -> str:
        return f'''using UnityEngine;

public class GeneratedScript : MonoBehaviour
{{
    // Generated for: {task}

    void Start()
    {{
        Debug.Log("TOM generated script started");
    }}

    void Update()
    {{
        // Frame update logic
    }}

    void OnCollisionEnter(Collision collision)
    {{
        // Handle collision
    }}
}}
'''

    def _unreal_script(self, task: str) -> str:
        return f'''#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "GeneratedActor.generated.h"

UCLASS()
class AGeneratedActor : public AActor
{{
    GENERATED_BODY()

public:
    AGeneratedActor()
    {{
        // Task: {task}
        PrimaryActorTick.bCanEverTick = true;
    }}

    virtual void BeginPlay() override
    {{
        Super::BeginPlay();
    }}

    virtual void Tick(float DeltaTime) override
    {{
        Super::Tick(DeltaTime);
    }}
}};
'''

    def _godot_script(self, task: str) -> str:
        return f'''extends Node2D

# Generated for: {task}

func _ready():
    print("TOM generated script ready")

func _process(delta):
    pass

func _input(event):
    if event is InputEventMouseButton:
        print("Clicked at: ", event.position)
'''

    def scaffold_fps(self, name: str) -> Dict[str, Any]:
        path = os.path.join(self.output_dir, name)
        os.makedirs(path, exist_ok=True)
        os.makedirs(os.path.join(path, "assets", "models"), exist_ok=True)
        os.makedirs(os.path.join(path, "assets", "sounds"), exist_ok=True)
        os.makedirs(os.path.join(path, "assets", "maps"), exist_ok=True)

        main_code = f'''"""
{name.replace("_", " ").title()} — FPS Game (PyGame)
Generated by TOM GameDev Engine
"""
import pygame
import sys
import math
import random

pygame.init()
W, H = 1024, 768
screen = pygame.display.set_mode((W, H))
pygame.display.set_caption("{name.replace('_', ' ').title()}")
clock = pygame.time.Clock()

BLACK = (0,0,0); WHITE = (255,255,255)
RED = (255,0,0); GREEN = (0,255,0); BLUE = (0,100,255)

class Player:
    def __init__(self):
        self.x = W//2; self.y = H//2
        self.angle = 0; self.hp = 100
        self.speed = 3; self.bullets = []
    def move(self, dx, dy):
        self.x = max(0, min(W, self.x + dx))
        self.y = max(0, min(H, self.y + dy))
    def shoot(self):
        self.bullets.append([self.x, self.y, self.angle])
    def update(self):
        for b in self.bullets[:]:
            b[0] += 10 * math.cos(b[2])
            b[1] += 10 * math.sin(b[2])
            if not (0 <= b[0] <= W and 0 <= b[1] <= H):
                self.bullets.remove(b)

class Enemy:
    def __init__(self):
        self.x = random.randint(50, W-50)
        self.y = random.randint(50, H-50)
        self.hp = 3; self.size = 15

player = Player()
enemies = [Enemy() for _ in range(5)]
score = 0
font = pygame.font.SysFont("Arial", 20)
running = True

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT: running = False
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_SPACE: player.shoot()
            if event.key == pygame.K_ESCAPE: running = False
    keys = pygame.key.get_pressed()
    dx = dy = 0
    if keys[pygame.K_w] or keys[pygame.K_UP]: dy = -player.speed
    if keys[pygame.K_s] or keys[pygame.K_DOWN]: dy = player.speed
    if keys[pygame.K_a] or keys[pygame.K_LEFT]: dx = -player.speed
    if keys[pygame.K_d] or keys[pygame.K_RIGHT]: dx = player.speed
    player.move(dx, dy)
    mx, my = pygame.mouse.get_pos()
    player.angle = math.atan2(my - player.y, mx - player.x)
    player.update()
    for e in enemies[:]:
        for b in player.bullets[:]:
            if math.hypot(b[0]-e.x, b[1]-e.y) < e.size:
                e.hp -= 1; player.bullets.remove(b)
                if e.hp <= 0: enemies.remove(e); score += 10
    screen.fill(BLACK)
    pygame.draw.circle(screen, BLUE, (int(player.x), int(player.y)), 10)
    for b in player.bullets:
        pygame.draw.circle(screen, WHITE, (int(b[0]), int(b[1])), 3)
    for e in enemies:
        pygame.draw.circle(screen, RED, (int(e.x), int(e.y)), e.size)
    screen.blit(font.render(f"HP: {{player.hp}} Score: {{score}}", True, WHITE), (10,10))
    pygame.display.flip()
    clock.tick(60)
pygame.quit(); sys.exit()
'''
        with open(os.path.join(path, "main.py"), "w") as f:
            f.write(main_code)
        with open(os.path.join(path, "requirements.txt"), "w") as f:
            f.write("pygame>=2.5.0\n")
        return {"status": "success", "path": path, "engine": "pygame", "game_type": "fps", "message": f"FPS game '{name}' scaffolded at {path}"}

    def scaffold_rpg(self, name: str) -> Dict[str, Any]:
        path = os.path.join(self.output_dir, name)
        os.makedirs(path, exist_ok=True)
        code = f'''"""
{name.replace("_", " ").title()} — RPG Game (PyGame)
Generated by TOM GameDev Engine
"""
import pygame, sys, random, math
pygame.init()
W, H = 800, 600
screen = pygame.display.set_mode((W, H))
pygame.display.set_caption("{name.replace('_', ' ').title()}")
clock = pygame.time.Clock()
BLACK=(0,0,0); WHITE=(255,255,255); GREEN=(34,139,34); BLUE=(0,100,255); GOLD=(255,215,0)

class Entity:
    def __init__(self,x,y,hp,color,size):
        self.x=x; self.y=y; self.hp=hp; self.max_hp=hp
        self.color=color; self.size=size; self.speed=3
    def move_toward(self,tx,ty):
        dx=tx-self.x; dy=ty-self.y; d=math.hypot(dx,dy)
        if d>2: self.x+=dx/d*self.speed; self.y+=dy/d*self.speed
    def draw(self):
        pygame.draw.circle(screen,self.color,(int(self.x),int(self.y)),self.size)
        bar_w=30; ratio=self.hp/self.max_hp
        pygame.draw.rect(screen,RED,(self.x-15,self.y-self.size-8,bar_w,4))
        pygame.draw.rect(screen,GREEN,(self.x-15,self.y-self.size-8,bar_w*ratio,4))

class Game:
    def __init__(self):
        self.player=Entity(W//2,H//2,100,BLUE,16)
        self.enemies=[Entity(random.randint(50,W-50),random.randint(50,H-50),20,RED,10) for _ in range(3)]
        self.items=[{"x":random.randint(50,W-50),"y":random.randint(50,H-50),"type":"gold"} for _ in range(5)]
        self.score=0; self.level=1; self.font=pygame.font.SysFont("Arial",18)
    def run(self):
        running=True
        while running:
            for event in pygame.event.get():
                if event.type==pygame.QUIT: running=False
                if event.type==pygame.KEYDOWN and event.key==pygame.K_ESCAPE: running=False
            keys=pygame.key.get_pressed()
            dx=dy=0
            if keys[pygame.K_w]: dy=-self.player.speed
            if keys[pygame.K_s]: dy=self.player.speed
            if keys[pygame.K_a]: dx=-self.player.speed
            if keys[pygame.K_d]: dx=self.player.speed
            self.player.x=max(10,min(W-10,self.player.x+dx))
            self.player.y=max(10,min(H-10,self.player.y+dy))
            for e in self.enemies[:]:
                e.move_toward(self.player.x,self.player.y)
                if math.hypot(self.player.x-e.x,self.player.y-e.y)<20:
                    self.player.hp-=0.5
            for item in self.items[:]:
                if math.hypot(self.player.x-item["x"],self.player.y-item["y"])<20:
                    self.items.remove(item); self.score+=50
            if len(self.enemies)==0:
                self.level+=1
                self.enemies=[Entity(random.randint(50,W-50),random.randint(50,H-50),20,RED,10) for _ in range(self.level+2)]
            screen.fill(BLACK)
            for item in self.items: pygame.draw.circle(screen,GOLD,(int(item["x"]),int(item["y"])),6)
            self.player.draw()
            for e in self.enemies: e.draw()
            screen.blit(self.font.render(f"HP:{self.player.hp} Score:{self.score} Lvl:{self.level}",True,WHITE),(10,10))
            pygame.display.flip()
            clock.tick(60)
        pygame.quit(); sys.exit()
Game().run()
'''
        with open(os.path.join(path, "main.py"), "w") as f:
            f.write(code)
        with open(os.path.join(path, "requirements.txt"), "w") as f:
            f.write("pygame>=2.5.0\n")
        return {"status": "success", "path": path, "engine": "pygame", "game_type": "rpg", "message": f"RPG game '{name}' scaffolded at {path}"}

    def scaffold_racing(self, name: str) -> Dict[str, Any]:
        path = os.path.join(self.output_dir, name)
        os.makedirs(path, exist_ok=True)
        code = f'''"""
{name.replace("_", " ").title()} — Racing Game (PyGame)
Generated by TOM GameDev Engine
"""
import pygame, sys, random, math
pygame.init()
W, H = 800, 600
screen = pygame.display.set_mode((W, H))
pygame.display.set_caption("{name.replace('_', ' ').title()}")
clock = pygame.time.Clock()
BLACK=(0,0,0); WHITE=(255,255,255); RED=(255,0,0); YELLOW=(255,255,0); GRAY=(100,100,100)

class Car:
    def __init__(self,x,y,color):
        self.x=x; self.y=y; self.color=color
        self.speed=0; self.max_speed=8; self.accel=0.2; self.brake=0.3; self.friction=0.05
        self.width=30; self.height=50
    def move(self,dx,dy):
        self.x+=dx; self.y+=dy
        self.x=max(self.width//2,min(W-self.width//2,self.x))
    def draw(self):
        pygame.draw.rect(screen,self.color,(self.x-self.width//2,self.y-self.height//2,self.width,self.height),border_radius=4)
        pygame.draw.rect(screen,YELLOW,(self.x-2,self.y-12,4,8))
        pygame.draw.rect(screen,RED,(self.x-2,self.y+4,4,8))

class Game:
    def __init__(self):
        self.player=Car(W//2,H-100,WHITE)
        self.obstacles=[]
        self.score=0; self.font=pygame.font.SysFont("Arial",24)
        self.spawn_timer=0; self.lanes=[W*0.25,W*0.5,W*0.75]
    def run(self):
        running=True
        while running:
            for event in pygame.event.get():
                if event.type==pygame.QUIT: running=False
                if event.type==pygame.KEYDOWN and event.key==pygame.K_ESCAPE: running=False
            keys=pygame.key.get_pressed()
            dx=0
            if keys[pygame.K_LEFT]: dx=-5
            if keys[pygame.K_RIGHT]: dx=5
            if keys[pygame.K_UP]: self.player.speed=min(self.player.max_speed,self.player.speed+self.player.accel)
            elif keys[pygame.K_DOWN]: self.player.speed=max(0,self.player.speed-self.player.brake)
            else: self.player.speed=max(0,self.player.speed-self.player.friction)
            self.player.move(dx,0)
            self.spawn_timer+=1
            if self.spawn_timer>30:
                self.obstacles.append({"x":random.choice(self.lanes),"y":-30,"color":RED})
                self.spawn_timer=0
            for o in self.obstacles[:]:
                o["y"]+=self.player.speed*0.5+2
                if o["y"]>H+30: self.obstacles.remove(o); self.score+=10
                elif math.hypot(self.player.x-o["x"],self.player.y-o["y"])<25:
                    self.obstacles.remove(o); self.score=max(0,self.score-30)
            screen.fill(BLACK)
            for i in range(0,H,60):
                pygame.draw.rect(screen,WHITE,(W//2-1,i,2,30))
            for o in self.obstacles:
                pygame.draw.circle(screen,o["color"],(int(o["x"]),int(o["y"])),15)
            self.player.draw()
            screen.blit(self.font.render(f"Speed: {{int(self.player.speed*12)}} km/h",True,WHITE),(10,10))
            screen.blit(self.font.render(f"Score: {{self.score}}",True,WHITE),(10,40))
            pygame.display.flip()
            clock.tick(60)
        pygame.quit(); sys.exit()
Game().run()
'''
        with open(os.path.join(path, "main.py"), "w") as f:
            f.write(code)
        return {"status": "success", "path": path, "engine": "pygame", "game_type": "racing", "message": f"Racing game '{name}' scaffolded at {path}"}

    def build_unity_project(self, name: str, template: str = "2D") -> Dict[str, Any]:
        path = os.path.join(self.output_dir, name)
        os.makedirs(os.path.join(path, "Assets", "Scripts"), exist_ok=True)
        os.makedirs(os.path.join(path, "Assets", "Scenes"), exist_ok=True)
        os.makedirs(os.path.join(path, "Assets", "Prefabs"), exist_ok=True)
        os.makedirs(os.path.join(path, "Assets", "Resources"), exist_ok=True)
        os.makedirs(os.path.join(path, "ProjectSettings"), exist_ok=True)
        return {"status": "success", "path": path, "engine": "unity", "message": f"Unity project structure at {path}"}
